/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useEffect, useRef, useState} from 'react';
import {
  Platform,
  Pressable,
  StyleSheet,
  Text,
  View,
  FlatList,
  Button,
  ListRenderItemInfo,
  RefreshControl,
  SafeAreaView,
} from 'react-native';
import {request, PERMISSIONS} from 'react-native-permissions';
import {SafeAreaProvider} from 'react-native-safe-area-context';

import {
  CameraData,
  RNFibriCheckVersion,
  RNFibriCheckView,
  RNCameraPreviewView,
} from '@fibricheck/react-native-camera-sdk';
import {createOAuth2Client, Document} from '@extrahorizon/javascript-sdk';
import {rqlBuilder} from '@extrahorizon/javascript-sdk';
import {
  FibriCheckViewHandle,
  SampleReadyEventData,
} from '@fibricheck/react-native-camera-sdk/build/types/src/FibriCheckView';

const credentials = {
  username: process.env.API_USER ?? '',
  password: process.env.API_PASS ?? '',
};

const sdk = createOAuth2Client({
  host: process.env.API_HOST ?? '',
  clientId: process.env.API_CLIENT_ID ?? '',
});

const schemaName = 'fibricheck-measurements';

type Screen = 'home' | 'app' | 'preview';

function renderDocument({
  item: {status, data, creationTimestamp},
}: ListRenderItemInfo<Document>) {
  return (
    <View style={styles.item}>
      <Text>{`${creationTimestamp.toLocaleString()} - ${status} - ${
        data.heartrate
      } - ${data.indicator}`}</Text>
    </View>
  );
}

const App = () => {
  const [screen, setScreen] = useState<Screen>('home');
  const [isFibriViewVisisble, setFibriViewVisible] = useState(false);
  const [isFingerPresent, setFingerPresent] = useState(false);
  const [isPulseDetected, setIsPulseDetected] = useState(false);
  const [isLoadingMeasurements, setLoadingMeasurements] = useState(false);
  const [hasCameraPermission, setCameraPermission] = useState(false);
  const [hasMeasurementStarted, setMeasurementStarted] = useState(false);
  const [heartRate, setHeartRate] = useState(0);
  const [timeRemaining, setTimeRemaining] = useState(60);
  const [measurements, setMeasurements] = useState<Document[]>([]);
  const userIdRef = useRef('');
  const fibriViewRef = useRef<FibriCheckViewHandle>(null);

  const retrieveMeasurements = async () => {
    setLoadingMeasurements(true);
    const rql = rqlBuilder()
      .limit(100)
      .eq('creatorId', userIdRef.current)
      .sort('-creationTimestamp')
      .build();
    const {data} = await sdk.data.documents.find(schemaName, {rql});
    setMeasurements(data);
    setLoadingMeasurements(false);
  };

  const authenticate = async () => {
    console.log('authenticate');
    console.log(await sdk.auth.authenticate(credentials));

    const user = await sdk.users.me();
    userIdRef.current = user.id;
    console.log('sdk.users.health()', await sdk.users.health());
    console.log('sdk.users.me()', user);

    await retrieveMeasurements();
  };

  const requestCameraPermissions = () => {
    if (Platform.OS === 'ios') {
      request(PERMISSIONS.IOS.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    } else {
      request(PERMISSIONS.ANDROID.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    }
  };

  const sendMeasurement = async (measurement: CameraData) => {
    const versionNew = RNFibriCheckVersion;

    try {
      const result = await sdk.data.documents.create(schemaName, {
        ...measurement,
        app: {
          name: 'mobile-spot-check',
          build: 1337,
          version: '2.11.2',
          camera_sdk_version: versionNew,
        },
        device: {
          os: '18.5',
          model: 'iPhone13,2',
          manufacturer: 'Apple',
          type: 'ios',
        },
        measurement_timestamp: new Date().getTime(),
      });

      retrieveMeasurements();

      console.log(`measurement created ${result.id}`);
    } catch (error) {
      console.warn(`measurement creation error`);
      console.warn(error);
    }
  };

  const onSampleReady = (event: SampleReadyEventData) => {
    /* Stub */
  };

  useEffect(() => {
    requestCameraPermissions();
    authenticate();
  }, []);

  if (screen === 'home') {
    return (
      <SafeAreaProvider style={styles.root}>
        <SafeAreaView style={[styles.flex, styles.homeContainer]}>
          <Text style={styles.homeTitle}>FibriCheck Camera SDK</Text>
          <Text style={styles.homeSubtitle}>Example App</Text>
          <View style={styles.homeButtons}>
            <Pressable
              style={styles.homeButton}
              onPress={() => setScreen('app')}>
              <Text style={styles.homeButtonText}>Normal App</Text>
            </Pressable>
            <Pressable
              style={styles.homeButton}
              onPress={() => setScreen('preview')}>
              <Text style={styles.homeButtonText}>Camera Preview</Text>
            </Pressable>
          </View>
        </SafeAreaView>
      </SafeAreaProvider>
    );
  }

  if (screen === 'preview') {
    return (
      <SafeAreaProvider style={styles.root}>
        <SafeAreaView style={styles.flex}>
          {hasCameraPermission && (
            <RNCameraPreviewView style={StyleSheet.absoluteFillObject} />
          )}
          <Pressable
            style={styles.backButton}
            onPress={() => setScreen('home')}>
            <Text style={styles.backButtonText}>← Back</Text>
          </Pressable>
          <View style={styles.previewLabel}>
            <Text style={styles.previewLabelText}>Standalone Preview</Text>
          </View>
        </SafeAreaView>
      </SafeAreaProvider>
    );
  }

  return (
    <SafeAreaProvider style={styles.root}>
      <SafeAreaView style={styles.flex}>
        <Pressable style={styles.backButton} onPress={() => setScreen('home')}>
          <Text style={styles.backButtonText}>← Back</Text>
        </Pressable>
        <View style={[styles.fibricontainer, styles.fibriview]}>
          <View style={styles.fibricontainer}>
            {hasCameraPermission && isFibriViewVisisble && (
              <RNFibriCheckView
                ref={fibriViewRef}
                style={styles.fibricontainer}
                graphBackgroundColor={'#0073ff'}
                flashEnabled={true}
                onFingerDetected={() => {
                  setFingerPresent(true);
                  console.log('Finger detected');
                }}
                onFingerRemoved={() => {
                  setFingerPresent(false);
                  console.log('Finger removed');
                }}
                onCalibrationReady={() => console.log('calibration ready')}
                onMeasurementFinished={() =>
                  console.log('measurement finished')
                }
                onMeasurementStart={() => {
                  setMeasurementStarted(true);
                  console.log('Measurement started');
                }}
                onFingerDetectionTimeExpired={() =>
                  console.log('finger detection time expired')
                }
                onPulseDetected={() => {
                  setIsPulseDetected(true);
                  console.log('Pulse detected');
                }}
                onPulseDetectionTimeExpired={() =>
                  console.log('pulse detection time is expired')
                }
                onMovementDetected={() => console.log('movement detected')}
                onHeartBeat={setHeartRate}
                onTimeRemaining={setTimeRemaining}
                onMeasurementError={event => console.log(event)}
                onMeasurementProcessed={sendMeasurement}
                onSampleReady={onSampleReady}
              />
            )}
          </View>
          <View>
            <Button
              onPress={() => {
                setFibriViewVisible(value => !value);
              }}
              color="#1E8D95"
              title={'Toggle'}
            />
          </View>
        </View>

        <View style={styles.container}>
          <View style={styles.row}>
            <Text>{`Heartrate : ${heartRate}`}</Text>
            <Text>{`Time Remaining: ${timeRemaining}`}</Text>
          </View>
          <View style={styles.row}>
            <Text>{`Finger present : ${isFingerPresent ? 'Yes' : 'No'}`}</Text>
            <Text>{`Pulse detected : ${isPulseDetected ? 'Yes' : 'No'}`}</Text>
          </View>
          <View style={styles.row}>
            <Text>{`Measurement Started : ${
              hasMeasurementStarted ? 'Yes' : 'No'
            }`}</Text>
          </View>
          <View style={[styles.row, styles.buttonRow]}>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.startMeasurement();
                }}
                color="#1E8D95"
                title={'Start'}
              />
            </View>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.resetModule();
                }}
                color="#1E8D95"
                title={'Reset'}
              />
            </View>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.startRecording();
                }}
                color="#1E8D95"
                title={'Record'}
              />
            </View>
          </View>

          <FlatList
            style={styles.list}
            data={measurements}
            renderItem={renderDocument}
            keyExtractor={item => item.id}
            refreshControl={
              <RefreshControl
                refreshing={isLoadingMeasurements}
                onRefresh={retrieveMeasurements}
              />
            }
          />
        </View>
      </SafeAreaView>
    </SafeAreaProvider>
  );
};

export default App;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  flex: {
    flex: 1,
  },

  // Home screen
  homeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  homeTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#263238',
  },
  homeSubtitle: {
    fontSize: 14,
    color: '#546E7A',
    marginBottom: 32,
  },
  homeButtons: {
    gap: 16,
    width: '70%',
  },
  homeButton: {
    backgroundColor: '#1E8D95',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  homeButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },

  // Back button (shared between app and preview screens)
  backButton: {
    margin: 12,
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: '#1E8D95',
    borderRadius: 8,
  },
  backButtonText: {
    color: 'white',
    fontWeight: '600',
  },

  // Preview screen
  previewLabel: {
    position: 'absolute',
    bottom: 32,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  previewLabelText: {
    color: 'white',
    fontSize: 13,
  },

  // Normal app screen
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 2,
  },
  buttonRow: {
    marginTop: 8,
  },
  commandButton: {
    borderRadius: 32,
    overflow: 'hidden',
    width: 86,
  },
  fibricontainer: {
    flex: 1,
    alignItems: 'stretch',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: 'hidden',
    backgroundColor: 'white',
  },
  fibriview: {
    backgroundColor: '#F5FCFF',
    marginHorizontal: 32,
    marginTop: 16,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    borderRadius: 32,
  },
  container: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF',
    paddingHorizontal: 32,
    paddingVertical: 16,
    gap: 2,
  },
  list: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  item: {
    width: '100%',
    backgroundColor: '#ECEFF1',
    padding: 8,
    marginVertical: 4,
    borderRadius: 32,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title: {
    fontSize: 32,
  },
});
