/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useEffect, useRef, useState} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  FlatList,
  Button,
  ListRenderItemInfo,
  RefreshControl,
  SafeAreaView,
  Switch,
} from 'react-native';
import {request, PERMISSIONS} from 'react-native-permissions';
import {SafeAreaProvider} from 'react-native-safe-area-context';

import {
  CameraData,
  RNFibriCheckVersion,
  RNFibriCheckView,
} from '@fibricheck/react-native-camera-sdk';
import {createOAuth2Client, Document} from '@extrahorizon/javascript-sdk';
import {rqlBuilder} from '@extrahorizon/javascript-sdk';
import {
  FibriCheckViewHandle,
  SampleReadyEventData,
} from '@fibricheck/react-native-camera-sdk/build/types/src/FibriCheckView';
import RNFS from 'react-native-fs';
import Share from "react-native-share";

/**
 * Saves a JSON object to a file in the app's document directory.
 *
 * @param {string} filename - Name of the file you want to write (e.g. "debug.json")
 * @param {object} data - Your JSON object
 * @returns {Promise<string>} The full path to the written file
 */
export async function saveJsonToFile(filename: string, data: object) {
  try {
    console.log(filename, data);
    // Convert data to a pretty JSON string
    const jsonString = JSON.stringify(data, null, 2);

    // Choose a platform-safe directory
    const path = `${RNFS.DocumentDirectoryPath}/${filename}`;

    // Write file (overwrites if exists)
    await RNFS.writeFile(path, jsonString, 'utf8');

    console.log(`JSON saved successfully at: ${path}`);
    // Create file:// URL for sharing
    const url = `file://${path}`;

    // Share options
    const options = {
      title: "Share JSON File",
      url,
      type: "application/json",
      failOnCancel: false,
    };

    // Open share sheet
    await Share.open(options);

    console.log("Shared file:", url);
    return path;
  } catch (err) {
    console.error('Error saving JSON:', err);
    throw err;
  }
}

const credentials = {
  username: process.env.API_USER ?? '',
  password: process.env.API_PASS ?? '',
};

const sdk = createOAuth2Client({
  host: process.env.API_HOST ?? '',
  clientId: process.env.API_CLIENT_ID ?? '',
});

const schemaId = '5a6f5d82454b300019e1df14';

function renderDocument({
  item: {status, data, creationTimestamp},
}: ListRenderItemInfo<Document>) {
  return (
    <View style={styles.item}>
      <Text>{`${creationTimestamp.toLocaleString()} - ${status} - ${
        data.heartrate
      } - ${data.indicator}`}</Text>
    </View>
  );
}

let lastLog = -1;

const App = () => {
  const [isFibriViewVisisble, setFibriViewVisible] = useState(false);
  const [isFingerPresent, setFingerPresent] = useState(false);
  const [isPulseDetected, setIsPulseDetected] = useState(false);
  const [isLoadingMeasurements, setLoadingMeasurements] = useState(false);
  const [hasCameraPermission, setCameraPermission] = useState(false);
  const [hasMeasurementStarted, setMeasurementStarted] = useState(false);
  const [heartRate, setHeartRate] = useState(0);
  const [timeRemaining, setTimeRemaining] = useState(60);
  const [measurements, setMeasurements] = useState<Document[]>([]);
  const [previewEnabled, setPreviewEnabled] = useState(false);
  const userIdRef = useRef('');
  const fibriViewRef = useRef<FibriCheckViewHandle>(null);

  const retrieveMeasurements = async () => {
    setLoadingMeasurements(true);
    const rql = rqlBuilder()
      .limit(100)
      .eq('creatorId', userIdRef.current)
      .sort('-creationTimestamp')
      .build();
    const {data} = await sdk.data.documents.find(schemaId, {rql});
    setMeasurements(data);
    setLoadingMeasurements(false);
  };

  const authenticate = async () => {
    console.log('authenticate');
    console.log(await sdk.auth.authenticate(credentials));

    const user = await sdk.users.me();
    userIdRef.current = user.id;
    console.log('sdk.users.health()', await sdk.users.health());
    console.log('sdk.users.me()', user);

    await retrieveMeasurements();
  };

  const requestCameraPermissions = () => {
    if (Platform.OS === 'ios') {
      request(PERMISSIONS.IOS.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    } else {
      request(PERMISSIONS.ANDROID.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    }
  };

  const sendMeasurement = async (measurement: CameraData) => {
    const versionDeprecated = RNFibriCheckView.versionNumber
    const versionNew = RNFibriCheckVersion
    
    try {
      await saveJsonToFile(`measurement-${Date.now()}.json`, measurement);
      const result = await sdk.data.documents.create(schemaId, {
        ...measurement,
        ...require('./extraData.json'),
        measurement_timestamp: new Date().getTime(),
        app: {
          camera_sdk_version: versionNew,
        }
      });

     

      // Refresh measurement list after creation
      retrieveMeasurements();

      console.log(`measurement created ${result.id}`);
    } catch (error) {
      console.warn(`measurement creation error`);
      console.warn(error);
    }
  };

  const onSampleReady = (event: SampleReadyEventData) => {
    /* Stub */
  };

  useEffect(() => {
    requestCameraPermissions();
    authenticate();
  }, []);

  return (
    <SafeAreaProvider style={styles.root}>
      <SafeAreaView style={styles.flex}>
        <View style={[styles.fibricontainer, styles.fibriview]}>
          <View style={styles.fibricontainer}>
            {hasCameraPermission && isFibriViewVisisble && (
              <RNFibriCheckView
                ref={fibriViewRef}
                style={styles.fibricontainer}
                graphBackgroundColor={'#0073ff'}
                flashEnabled={true}
                onFingerDetected={() => {
                  setFingerPresent(true);
                  console.log('Finger detected');
                }}
                onFingerRemoved={() => {
                  setFingerPresent(false);
                  console.log('Finger removed');
                }}
                onCalibrationReady={() => console.log('calibration ready')}
                onMeasurementFinished={() =>
                  console.log('measurement finished')
                }
                onMeasurementStart={() => {
                  setMeasurementStarted(true);
                  console.log('Measurement started');
                }}
                onFingerDetectionTimeExpired={() =>
                  console.log('finger detection time expired')
                }
                onPulseDetected={() => {
                  setIsPulseDetected(true);
                  console.log('Pulse detected');
                }}
                onPulseDetectionTimeExpired={() =>
                  console.log('pulse detection time is expired')
                }
                onRawData={(image, metadata) => {
                  const delta = Date.now() - lastLog
                  if (delta < 1000) {
                    return;
                  }
                  lastLog = Date.now()

                  if (Platform.OS === 'ios') {
                    const hdr = metadata['isHdrEnabled']
                    const focus = metadata['lensPosition']
                    const exposureTime = metadata['exposureTime']
                    const iso = metadata['iso']
                    const whiteBalance = metadata['whiteBalanceGains']

                    console.log(`Image bytes: ${image.length} HDR: ${hdr}, ISO: ${iso}, Exposure: ${exposureTime}, Focus: ${focus}, White Balance: ${whiteBalance}`)
                  }
                }}
                onMovementDetected={() => console.log('movement detected')}
                onHeartBeat={setHeartRate}
                onTimeRemaining={setTimeRemaining}
                onMeasurementError={event => console.log(event)}
                onMeasurementProcessed={sendMeasurement}
                onSampleReady={onSampleReady}
                cameraSettings={{
                  whiteBalanceMode: 'auto',
                  focusMode: 'auto',
                  exposureMode: 'auto',
                  whiteBalanceRgb: [1, 1, 1],
                  rawDataEnabled: true,

                  logExposure: true,
                  logFocus: true,
                  logWhiteBalance: true
                }}
                sampleTime={35}
                preview={previewEnabled}
              />
            )}
          </View>
          <View>
            <Button
              onPress={() => {
                setFibriViewVisible(value => !value);
              }}
              color="#1E8D95"
              title={'Toggle'}
            />
          </View>
        </View>

        <View style={styles.container}>
          <View style={styles.row}>
            <Text>{`Heartrate : ${heartRate}`}</Text>
            <Text>{`Time Remaining: ${timeRemaining}`}</Text>
          </View>
          <View style={styles.row}>
            <Text>{`Finger present : ${isFingerPresent ? 'Yes' : 'No'}`}</Text>
            <Text>{`Pulse detected : ${isPulseDetected ? 'Yes' : 'No'}`}</Text>
          </View>
          <View style={styles.row}>
            <Text>{`Measurement Started : ${
              hasMeasurementStarted ? 'Yes' : 'No'
            }`}</Text>
          </View>
          <View style={[styles.row, styles.buttonRow]}>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.startMeasurement();
                }}
                color="#1E8D95"
                title={'Start'}
              />
            </View>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.resetModule();
                }}
                color="#1E8D95"
                title={'Reset'}
              />
            </View>
            <View style={styles.commandButton}>
              <Button
                onPress={() => {
                  fibriViewRef.current?.startRecording();
                }}
                color="#1E8D95"
                title={'Record'}
              />
            </View>
          </View>

          <View style={styles.row}>
            <Switch value={previewEnabled} onChange={(e) => setPreviewEnabled(e.nativeEvent.value)} />
            <Text>Preview Enabled</Text>
          </View>

          <FlatList
            style={styles.list}
            data={measurements}
            renderItem={renderDocument}
            keyExtractor={item => item.id}
            refreshControl={
              <RefreshControl
                refreshing={isLoadingMeasurements}
                onRefresh={retrieveMeasurements}
              />
            }
          />
        </View>
      </SafeAreaView>
    </SafeAreaProvider>
  );
};

export default App;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    display: 'flex',
    backgroundColor: '#F5FCFF',
  },
  flex: {
    flex: 1,
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 2,
  },
  buttonRow: {
    marginTop: 8,
  },
  commandButton: {
    borderRadius: 32,
    overflow: 'hidden',
    width: 86,
  },
  fibricontainer: {
    flex: 1,
    display: 'flex',
    alignItems: 'stretch',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: 'hidden',
    backgroundColor: 'white',
  },
  fibriview: {
    backgroundColor: '#F5FCFF',
    marginHorizontal: 32,
    marginTop: 16,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    borderRadius: 32,
  },
  container: {
    flex: 1,
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF',
    paddingHorizontal: 32,
    paddingVertical: 16,
    gap: 2,
  },
  list: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  item: {
    width: '100%',
    backgroundColor: '#ECEFF1',
    padding: 8,
    marginVertical: 4,
    borderRadius: 32,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  title: {
    fontSize: 32,
  },
});
