/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {useCallback, useEffect, useRef, useState} from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  FlatList,
  Button,
  ListRenderItemInfo,
  RefreshControl,
  SafeAreaView,
} from 'react-native';
import {request, PERMISSIONS} from 'react-native-permissions';
import {SafeAreaProvider} from 'react-native-safe-area-context';

import {
  CameraData,
  RNFibriCheckView,
} from '@fibricheck/react-native-camera-sdk';
import {createOAuth2Client, Document} from '@extrahorizon/javascript-sdk';
import {rqlBuilder} from '@extrahorizon/javascript-sdk';
import {SampleReadyEventData} from '@fibricheck/react-native-camera-sdk/build/types/src/FibriCheckView';

const credentials = {
  username: process.env.API_USER ?? '',
  password: process.env.API_PASS ?? '',
};

const sdk = createOAuth2Client({
  host: process.env.API_HOST ?? '',
  clientId: process.env.API_CLIENT_ID ?? '',
});

const schemaId = '5a6f5d82454b300019e1df14';
const maxBufferLength = 100;

interface GraphPoint {
  x: number;
  y: number;
}

interface Domain {
  min: number;
  max: number;
}

function renderDocument({
  item: {status, data, creationTimestamp},
}: ListRenderItemInfo<Document>) {
  return (
    <View style={styles.item}>
      <Text>{`${creationTimestamp.toLocaleString()} - ${status} - ${
        data.heartrate
      } - ${data.indicator}`}</Text>
    </View>
  );
}

const App = () => {
  const [isFibriViewVisisble, setFibriViewVisible] = useState(false);
  const [isFingerPresent, setFingerPresent] = useState(false);
  const [isPulseDetected, setIsPulseDetected] = useState(false);
  const [isLoadingMeasurements, setLoadingMeasurements] = useState(false);
  const [hasCameraPermission, setCameraPermission] = useState(false);
  const [hasMeasurementStarted, setMeasurementStarted] = useState(false);
  const [heartRate, setHeartRate] = useState(0);
  const [timeRemaining, setTimeRemaining] = useState(60);
  const [domain, setDomain] = useState<Domain>({min: 0, max: 0});
  const [measurements, setMeasurements] = useState<Document[]>([]);
  const graphData = useRef<GraphPoint[]>([]);
  const userIdRef = useRef('');

  const retrieveDocuments = useCallback(async () => {
    setLoadingMeasurements(true);
    const rql = rqlBuilder().limit(100).eq('creatorId', userIdRef.current).sort('-creationTimestamp').build();
    const {data} = await sdk.data.documents.find(schemaId, {rql});
    data.sort(
      (a, b) => b.creationTimestamp.getTime() - a.creationTimestamp.getTime(),
    );
    setMeasurements(data);
    setLoadingMeasurements(false);
  }, []);

  const authenticate = useCallback(async () => {
    console.log('authenticate');
    console.log(await sdk.auth.authenticate(credentials));

    const user = await sdk.users.me();
    userIdRef.current = user.id;
    console.log('sdk.users.health()', await sdk.users.health());
    console.log('sdk.users.me()', user);

    await retrieveDocuments();
  }, [retrieveDocuments]);

  const requestCameraPermissions = useCallback(() => {
    if (Platform.OS === 'ios') {
      request(PERMISSIONS.IOS.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    } else {
      request(PERMISSIONS.ANDROID.CAMERA).then(result => {
        setCameraPermission(result === 'granted');
      });
    }
  }, []);

  const sendMeasurement = useCallback(
    async (measurement: CameraData) => {
      console.log('sendMeasurement');
      try {
        const result = await sdk.data.documents.create(schemaId, {
          ...measurement,
          ...require('./extraData.json'),
          measurement_timestamp: new Date().getTime(),
        });

        console.log(`measurement created ${result.id}`);
      }
      catch (error) {
        console.warn(error);
      }

      retrieveDocuments();
    },
    [retrieveDocuments],
  );

  const updateDomain = useCallback(() => {
    console.log('updateDomain');
    if (graphData.current.length === 0) {
      return;
    }

    const lastPoint = graphData.current[graphData.current.length - 1];
    if (lastPoint.x < 50) {
      return;
    }

    setDomain({
      min: domain.min + 1,
      max: domain.max + 1,
    });
  }, [domain]);

  const onSampleReady = useCallback(
    (event: SampleReadyEventData) => {
      console.log('onSampleReady');
      const data = graphData.current;
      const newX = data.length > 0 ? data[data.length - 1].x + 1 : 0;
      data.push({
        x: newX,
        y: event.ppg,
      });
      graphData.current = data.slice(-maxBufferLength);
      updateDomain();
    },
    [updateDomain],
  );

  useEffect(() => {
    requestCameraPermissions();
    authenticate();
  }, [authenticate, requestCameraPermissions]);

  return (
    <SafeAreaProvider style={styles.root}>
      <SafeAreaView style={styles.flex}>
      <View style={[styles.fibricontainer, styles.fibriview]}>
        <View style={styles.fibricontainer}>
          {hasCameraPermission && isFibriViewVisisble && (
            <RNFibriCheckView
              style={styles.fibricontainer}
              graphBackgroundColor={'#0073ff'}
              flashEnabled={true}
              onFingerDetected={() => {
                setFingerPresent(true);
                console.log('Finger detected');
              }}
              onFingerRemoved={() => {
                setFingerPresent(false);
                console.log('Finger removed');
              }}
              onCalibrationReady={() => console.log('calibration ready')}
              onMeasurementFinished={() => console.log('measurement finished')}
              onMeasurementStart={() => {
                setMeasurementStarted(true);
                console.log('Measurement started');
              }}
              onFingerDetectionTimeExpired={() =>
                console.log('finger detection time expired')
              }
              onPulseDetected={() => {
                setIsPulseDetected(true);
                console.log('Pulse detected');
              }}
              onPulseDetectionTimeExpired={() =>
                console.log('pulse detection time is expired')
              }
              onMovementDetected={() => console.log('movement detected')}
              onHeartBeat={setHeartRate}
              onTimeRemaining={setTimeRemaining}
              onMeasurementError={event => console.log(event)}
              onMeasurementProcessed={sendMeasurement}
              onSampleReady={onSampleReady}
            />
          )}
        </View>
        <View style={styles.button}>
          <Button
            onPress={() => {
              console.log('setFibriViewVisiblee');
              setFibriViewVisible(value => !value);
            }}
            color="#1E8D95"
            title={'Toggle'}
          />
        </View>
      </View>

      <View style={styles.container}>
        <View style={styles.row}>
          <Text>{`Heartrate : ${heartRate}`}</Text>
          <Text>{`Time Remaining: ${timeRemaining}`}</Text>
        </View>
        <View style={styles.row}>
          <Text>{`Finger present : ${isFingerPresent ? 'Yes' : 'No'}`}</Text>
          <Text>{`Pulse detected : ${isPulseDetected ? 'Yes' : 'No'}`}</Text>
        </View>
        <View style={styles.row}>
          <Text>{`Measurement Started : ${
            hasMeasurementStarted ? 'Yes' : 'No'
          }`}</Text>
        </View>



        <FlatList
          style={styles.list}
          data={measurements}
          renderItem={renderDocument}
          keyExtractor={item => item.id}
          refreshControl={<RefreshControl refreshing={isLoadingMeasurements} onRefresh={retrieveDocuments} />}
        />
        <View style={styles.button}>
          <Button
            title={'Retrieve'}
            onPress={retrieveDocuments}
            color="#1E8D95"
          />
        </View>

      </View>
      </SafeAreaView>
    </SafeAreaProvider>
  );
};

export default App;

const styles = StyleSheet.create({
  root: {
    flex: 1,
    display: 'flex',
    backgroundColor: '#F5FCFF',
  },
  flex: {
    flex: 1,
  },
  button: {
    borderRadius: 32,
    overflow: 'hidden',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fibricontainer: {
    flex: 1,
    display: 'flex',
    alignItems: 'stretch',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    overflow: 'hidden',
    backgroundColor: 'white',
  },
  fibriview: {
    backgroundColor: '#F5FCFF',
    marginHorizontal: 32,
    marginTop: 16,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    borderRadius: 32,
  },
  container: {
    flex: 1,
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF',
    paddingHorizontal: 32,
    paddingVertical: 16,
    gap: 2,
  },
  list: {
    width: '100%',
    marginTop: 8,
    marginBottom: 8,
  },
  item: {
    width: '100%',
    backgroundColor: '#ECEFF1',
    padding: 8,
    marginVertical: 4,
    borderRadius: 32,
    borderColor: '#CFD8DC',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 2,
  },
  title: {
    fontSize: 32,
  },
});
