name: Build & deploy to development
on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    environment: 
      name: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Expose project info
        run: |
          echo "PROJECT_NAME=`jq -r '.name' ./documentation/project_info.json`" >> $GITHUB_ENV
          echo "PROJECT_VERSION=`jq -r '.version' ./documentation/project_info.json`" >> $GITHUB_ENV
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
          echo "@extrahorizon:registry=https://npm.pkg.github.com" >> .npmrc
          
        env:
         NPM_TOKEN: ${{ secrets.NPM_PACKAGES_FULL_READ_ACCESS_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_FULL_READ_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'

      - name: Transpile & publish
        run: |
          yarn
          # yarn q-license-check
          yarn audit --level high 2>/dev/null || echo "audit DONE"
          # yarn lint
          yarn --production
